# Generated by Django 3.1.1 on 2020-09-20 18:24

from django.contrib.auth.models import User
from django.db import migrations, models
from django.conf import settings

def create_superusers(apps, schema):
    # Create default superusers
    superuser = User.objects.create_superuser(
            username=settings.SU_DEFAULT_USERNAME,
            email=settings.SU_DEFAULT_EMAIL,
            password=settings.SU_DEFAULT_PASSWORD)

    superuser.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=63, verbose_name='Name')),
                ('facade_image', models.ImageField(default='', upload_to='media/organization/facade_image', verbose_name='Facade image')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.RunPython(create_superusers, migrations.RunPython.noop),
    ]
