# Generated by Django 3.1.1 on 2020-09-20 19:13
from random import choice
from string import ascii_letters, digits
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion

CHAR_SUPERSET = ascii_letters + digits

CITIES = (
    ('Moscow', 55.7558, 37.6173),
    ('London', 51.5074, 0.1278),
    ('Beijing', 39.9042, 116.4074),
    ('Berlin', 52.5200, 13.4050),
    ('Madrid', 40.4168, 3.7038),
    ('New-York', 40.7128, 74.0060),
    ('Los Angeles', 34.0522, 118.2437),
    ('Pretoria', 25.7479, 28.2293),
    ('Dubai', 25.2048, 55.2708),
    ('Canberra', 35.4735, 149.0124),
)

def create_mock_branches(apps, schema_editor):
    Branch = apps.get_model('organization', 'Branch')
    branch_list = []
    for i, city in enumerate(CITIES):
        branch = Branch(
            name=city[0],
            latitude=Decimal(city[1]),
            longitude=Decimal(city[2])
        )
        branch.save()
        branch_list.append(branch)
    return branch_list

def create_mock_employees(apps, schema_editor):
    '''
    Create mock Employee and Branch data
    '''

    branch_list = create_mock_branches(apps, schema_editor)

    Employee = apps.get_model('organization', 'Employee')
    for i in range(10000):
        random_string = ''.join(choice(CHAR_SUPERSET) for j in range(16))
        employee = Employee(
            first_name=f'Mock_Employee_FName_{random_string}',
            third_name=f'Mock_Employee_FName_{random_string}',
            position_title=f'Mock_Employee_FName_{random_string}',
            branch=choice(branch_list)
        )
        employee.save()

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=40, verbose_name='First Name')),
                ('third_name', models.CharField(default='', max_length=40, verbose_name='Third Name')),
                ('position_title', models.CharField(default='', max_length=40, verbose_name='Position Title')),
                ('branch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_list', to='organization.branch', verbose_name='Branch')),
            ],
        ),
        migrations.RunPython(create_mock_employees, migrations.RunPython.noop) 
    ]
